In [1]:
import numpy as np
l = []
n = int(input("Введите кол-во строк: "))
m = int(input("Введите кол-во стлбцов "))
mat = np.random.rand(n, m)
print("Исходная матрица:\n", mat)
for i in mat:
    for j in i:
        l.append(round(j, 8))

print("Конечная матрица:\n", l)


Исходная матрица:
 [[0.08918884 0.58800531 0.85001384]
 [0.60338243 0.12935327 0.80482657]
 [0.62213874 0.60076039 0.52979626]]
Конечная матрица:
 [0.08918884, 0.58800531, 0.85001384, 0.60338243, 0.12935327, 0.80482657, 0.62213874, 0.60076039, 0.52979626]
