In [1]:
import numpy as np
l = []
n = int(input("Введите кол-во строк: "))
m = int(input("Введите кол-во стлбцов "))
mat = np.random.rand(n, m)
print("Исходная матрица:\n", mat)
for i in mat:
    for j in i:
        l.append(round(j, 8))

print("Конечная матрица:\n", l)


Исходная матрица:
 [[0.53470418 0.58246917 0.73052326 0.75501774]
 [0.41100978 0.18135442 0.76424319 0.94132555]
 [0.52730753 0.25060803 0.85691326 0.53184822]
 [0.77153835 0.09174248 0.95798867 0.45335839]]
Конечная матрица:
 [0.53470418, 0.58246917, 0.73052326, 0.75501774, 0.41100978, 0.18135442, 0.76424319, 0.94132555, 0.52730753, 0.25060803, 0.85691326, 0.53184822, 0.77153835, 0.09174248, 0.95798867, 0.45335839]
